# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('tipo', models.TextField(choices=[('DISSERTACAO', 'Dissertação'), ('TESE', 'Tese'), ('LIVRE_DOCENCIA', 'Livre docência')])),
                ('autor', models.TextField()),
                ('unidade', models.TextField()),
                ('area_conhecimento', models.TextField()),
                ('data_defesa', models.DateField()),
                ('ano_publicacao', models.IntegerField()),
                ('orientador', models.TextField()),
                ('palavras_chaves', models.TextField()),
            ],
        ),
    ]
