# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160630_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacao',
            old_name='downlaods',
            new_name='downloads',
        ),
    ]
