# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160702_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
