# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_publicacao_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='tipo',
            field=models.TextField(choices=[('DISSERTACAO_METRADO', 'Dissertação de Mestrado'), ('TESE_DOUTORADO', 'Tese de Doutorado'), ('TESE_LIVRE_DOCENCIA', 'Tese de Livre Docencia')]),
        ),
    ]
